### ISSUE TITLE
webpack hard codes NODE_ENV

### ISSUE THREAD

**Issue by baldurh** [ueno-llc/starter-kit#22]
The define plugin is hard coding the `NODE_ENV` env variable to whatever it is during build.
That means you cannot run a build in any other environment than the one it was built in.
See here:
https://github.com/ueno-llc/starter-kit/blob/master/webpack/make.js#L151

**Comment by birkir** [comment]
We currently build using specific environment, like for instance when in `development` we get different version of React than in `production`.

I did a little test and built a NODE_ENV=production build without hard-coding the variable in, then tried changing to `staging` and `development` and got warnings about using minified version of react, etc.

Do we have any use-case for this now?
