### ISSUE TITLE
Single-quotes aren't properly escaped in __INITIAL_STATE__?

### ISSUE THREAD

**Issue by elliottkember** [ueno-llc/starter-kit#26]
I've got some content with a ' character in it which isn't escaped in the `window.__INITIAL_STATE__ =` line. This might have to be `window.__INITIAL_STATE__ = '${state.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}';` or base64 en/decoded?

**Comment by birkir** [comment]
Allright, this was making serious bugs for us in other projects as well.

Fixed with https://github.com/ueno-llc/starter-kit/commit/7a80bb5dc09ff331930565610f58bef1a2361145
